likes/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'likes.views',
    url(r'^like/(?P<content_type>[\w-]+)/(?P<id>\d+)/(?P<vote>-?\d+)$', 'like',
        name='like'),
)

melaongo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^blog/$', views.post_list, name='post_list'),
    url(r'^blog/post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^blog/post/new/$', views.post_new, name='post_new'),
    url(r'^blog/post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^blog/drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^blog/post/(?P<pk>[0-9]+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^blog/post/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^blog/post/(?P<pk>[0-9]+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^blog/comment/(?P<pk>[0-9]+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^blog/comment/(?P<pk>[0-9]+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^blog/about/$',views.blog_about, name='blog_about'),
    url(r'^blog/contact/$',views.blog_contact, name='blog_contact'),
    #url(r'^blog/',views.blog),
    #url(r'^blog/post/(?P<pk>[0-9]+)/$', views.blog_post_detail, name='blog_post_detail'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^blog/accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/blog'}),
    url(r'', include('melaongo.urls')),
    url(r'^likes/', include('likes.urls')),
    url(r'^accounts/', include('allauth.urls')),
]

melaongo/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
import secretballot

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
        
    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title

secretballot.enable_voting_on(Post)

class Comment(models.Model):
    post = models.ForeignKey('melaongo.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

melaongo/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)
        

class ContactForm(forms.Form):
    #contact_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-group col-xs-12 floating-label-form-group controls'}))
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    #contact_number = forms.CharField(widget=forms.TextInput(attrs={'type':'number'}))
    contact_number = forms.CharField(required=True)
    contact_message = forms.CharField(required=True,widget=forms.Textarea)

melaongo/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render_to_response
from django.utils import timezone
from .models import Post, Comment
from .forms import PostForm, CommentForm, ContactForm

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.template import Context

from likes.middleware import SecretBallotUserIpUseragentMiddleware

# Create your views here.

#######################################################################
#                     Clean Blog content                              #
#######################################################################

def blog_contact(request):
    form_class = ContactForm

    # new logic!
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get('contact_name', '')
            contact_email = request.POST.get('contact_email', '')
            contact_number = request.POST.get('contact_number', '')
            contact_message = request.POST.get('contact_message', '')

            # Email the profile with the 
            # contact information
            template = get_template('blog/contact_template.txt')
            context = Context({'contact_name': contact_name, 'contact_email': contact_email,'contact_number': contact_number, 'contact_message': contact_message,})
            content = template.render(context)
            #print content

            email = EmailMessage(
                "Message from MELAONGO",
                content,
                " melaongo " +'<melaongo.heroku.com>',
                ['srinaveen.desu@gmail.com'],
                headers = {'Reply-To': contact_email }
            )
            email.send()
            return redirect('melaongo.views.blog_contact')
        
    return render(request, 'blog/blog_contact.html', {'form': form_class,})

def blog_about(request):
    #return render_to_response('blog/blog_about.html')
    return render(request, 'blog/blog_about.html')

##def blog(request):
##    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
##    return render(request, 'blog/blog.html', {'posts': posts})
##
##def blog_post_detail(request, pk):
##    post = get_object_or_404(Post, pk=pk)
##    return render(request, 'blog/post.html', {'post': post})


#######################################################################
#                    Normal Blog content                              #
#######################################################################


def post_list(request):
    posts_list = Post.objects.all().filter(published_date__lte=timezone.now()).order_by('published_date').reverse()
    paginator = Paginator(posts_list, 25)

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    sbp = SecretBallotUserIpUseragentMiddleware()
    sbp.process_request(request)
        
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    sbp = SecretBallotUserIpUseragentMiddleware()
    sbp.process_request(request)
    
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            #post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_add.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('melaongo.views.post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('melaongo.views.post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('melaongo.views.post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('melaongo.views.post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('melaongo.views.post_detail', pk=post_pk)

melaongo/templates/blog/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	
        <title>Melaongo blog</title>
		
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

		
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'melaongo.views.post_list' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'melaongo.views.blog_about' %}">About</a>
                    </li>

    
        {% if user.is_authenticated %}
        <li><a href="{% url 'post_new' %}"><span class="glyphicon glyphicon-plus"></span></a></li>
        <li><a href="{% url 'post_draft_list' %}" ><span class="glyphicon glyphicon-edit"></span></a></li>

                    <li>
                        <a href="{% url 'melaongo.views.post_list' %}">Contact</a>
                    </li>
					
		<li><a href="{% url 'django.contrib.auth.views.logout' %}">Log out</a></li>
		
        {% else %}
                    <li>
                        <a href="{% url 'melaongo.views.post_list' %}">Contact</a>
                    </li>
        <li><a href="{% url 'django.contrib.auth.views.login' %}"><span class="glyphicon glyphicon-lock"></span></a></li>
		
        {% endif %}
					
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/about-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Web Developer - A programmer who specializes in, or is specifically engaged in, the development of World Wide Web applications, or distributed network applications that are run over HTTP from a web server to a web browser.</p>
                <p>App Developer - A person who develops stand-alone software (that is more than just a simple program) and gets involved with all phases of the development (design and code) is a software developer.</p>
                <p>Pythonist - Python is the one of the leading programming languages used in all facets of the programming world. It can be utilized in building amazing web applications, desktop applications(GUI), Scientific endeavors, database applications and much more.</p>
            </div>
        </div>
    </div>

    <hr>

	    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://twitter.com/srinaveen_desu">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="http://www.facebook.com/srinaveen.desu">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="http://github.com/srinaveendesu">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Srinaveen Desu 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
	
</body>

</html>

melaongo/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
	
        <!-- {{ form.as_p }} !-->
         <!--
        <p><label for="id_author">Author:</label> <input id="id_author" maxlength="200" name="author" type="text" /></p>
<p><label for="id_text">Text:</label> <textarea cols="40" id="id_text" name="text" rows="10">
</textarea></p>		
		!-->
		
					<div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_author">Author</label>
                            <input type="text" class="form-control" name="author" placeholder="Author" id="id_author" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_text">Comment</label>
                            <textarea rows="5" class="form-control" name="text" placeholder="Comment" id="id_text" required data-validation-required-message="Please enter a Comment."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    	
		
		
        <button type="submit" class="save btn btn-default">Send</button>
    </form>

	
{% endblock %}

melaongo/templates/blog/blog_contact.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	
        <title>Melaongo blog</title>
		
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

		
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'melaongo.views.post_list' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'melaongo.views.blog_about' %}">About</a>
                    </li>

    
        {% if user.is_authenticated %}
        <li><a href="{% url 'post_new' %}"><span class="glyphicon glyphicon-plus"></span></a></li>
        <li><a href="{% url 'post_draft_list' %}" ><span class="glyphicon glyphicon-edit"></span></a></li>

                    <li>
                        <a href="{% url 'melaongo.views.blog_contact' %}">Contact</a>
                    </li>
					
		<li><a href="{% url 'account_logout' %}">Log out</a></li>
		
        {% else %}
                    <li>
                        <a href="{% url 'melaongo.views.blog_contact' %}">Contact</a>
                    </li>
        <li><a href="{% url 'account_login' %}"><span class="glyphicon glyphicon-lock"></span></a></li>
		
        {% endif %}
					
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/contact-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
				<form role="form" action="" method="post">
					{% csrf_token %}
					<!-- 	{{ form.as_p }} 	!-->
					
					<div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_contact_name">Name</label>
                            <input type="text" class="form-control" placeholder="Name" name="contact_name" id="id_contact_name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>

					<div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_contact_email">Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" name="contact_email" id="id_contact_email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
					
					<div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_contact_number">Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" name="contact_number" id="id_contact_number" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
					
					<div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_contact_message">Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" name="contact_message" id="id_contact_message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>

					<div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>

					
					<!--         <button type="submit">Submit</button>         !-->
				</form>
            </div>
        </div>
    </div>

    <hr>

	    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
					
					<ul class="social-network social-circle">
                   
                   <!--     <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>    -->
                        <li><a href="http://www.facebook.com/srinaveen.desu" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://twitter.com/srinaveen_desu" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://google.com/+SrinaveenDesu" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="https://in.linkedin.com/in/srinaveendesu" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="http://github.com/srinaveendesu" class="icoGithub" title="Github"><i class="fa fa-github"></i></a></li>               
                       
                    </ul>
						
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Srinaveen Desu 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
	
</body>

</html>

melaongo/templates/blog/post_add.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
	
	<!--  {{ form.as_p }}   !-->
				
				  
					<div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_title">Title</label>
                            <input type="text" class="form-control" name="title" placeholder="Title" id="id_title"  required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    
					
                 
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_text">Text</label>
                            <textarea rows="5" class="form-control" name="text" placeholder="Message" id="id_text" required data-validation-required-message="Please enter a Comment."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>

        
  

			
					
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

melaongo/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
	
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'melaongo.views.post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
	<hr>
	
    {% endfor %}
{% endblock %}

melaongo/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}